name: Check dependencies update

on:
  workflow_dispatch:
  repository_dispatch:
    types: [check_update]

jobs:
  check-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      
      - run: |
          echo ${{ github.event.client_payload.ref }}
          echo ${{ github.event.client_payload.sha }}
      
      - name: npm depcheck
        uses: tj-actions/depcheck@v7.2
        with:
          ignores: 'eslint,babel-*'
