name: Check dependencies update

on:
  workflow_dispatch:
  repository_dispatch:
    types: [check_update]

jobs:
  check-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      
      - run: |
          echo ${{ github.event.client_payload.ref }}
          echo ${{ github.event.client_payload.sha }}
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
        
      - name: Update dependencies
        uses: neverendingqs/gh-action-node-update-deps@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
