name: Deploy to github pages

on:
  push:
    branches:
      - master
  workflow_dispatch:


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
      - run: npm install
      - run: npm run build
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v2.3.0
        with:
          build_dir: build
        env:
          GITHUB_TOKEN:
            ${{ secrets.PA_TOKEN }}
